const MENU_LANGUAGES = [
  [
    'Focused Attention Games',
    'Selective Attention Games',
    'Divided Attention Games',
    'Sustained Attention Games',
    'Auditory Attention',
    'Report Summary',
    'Select your favourite animal',
    'Click on the animal appearing on the screen',
    'Choose this from below',
    'Click on the below image when 2 images match',
    'Click on the button when the animal rests',
    'Attention Games',
    'Need To Improve',
    'Good',
    'Very Good',
    'As per the observation, Child is in good health.',
    'As per the observation, The Child needs more attention.',
    'Well Done',
    'Not Good', // 18
    'Go back to Menu', // 19
    'Average taking time  by a normal child for a single response',
    'Time taken by your child for a single response',
    'Your child is very good',
    'Your child is good, Try to improve',
    'Your child need more attention',
    'You',
    ' Won Game',
    ' Lost Game', // 27
    'Go To Next',
    'Go to Result',
    'Level',
    'This leve for age 5',
    'This leve for age 6',
    'This leve for age 7',
    'Go Back To Menu', // 34
    'Take Screenshot',
  ],
  [
    'අවධානය යොමු කරන ක්‍රීඩා',
    'තේරීම් අවධානය යොමු කිරීමේ ක්‍රීඩා',
    'බෙදාගත් අවධානය යොමු කිරීමේ ක්‍රීඩා',
    'දිගු අවධානය යොමු කිරීමේ ක්‍රීඩා',
    'හඩ අවධානය යොමු කිරීමේ ක්‍රීඩා',
    'වාර්තාවේ සාරාංශය',
    'ඔබ කැමති සතා තෝරන්න',
    'තිරයේ දිස්වන සත්වයා මත ක්ලික් කරන්න',
    'පහතින් මෙය තෝරන්න',
    'පින්තූර 2ක් ගැලපෙන විට පහත රූපය මත ක්ලික් කරන්න',
    'සත්වයා විවේක ගන්නා විට බොත්තම මත ක්ලික් කරන්න',
    'කල්පනාවෙන් කරන සෙල්ලම්',
    'වැඩිදියුණු කිරීමට අවශ්‍යයි',
    'හොඳයි',
    'ඉතා හොඳයි',
    'නිරීක්ෂණයට අනුව දරුවා යහපත් සෞඛ්‍ය තත්ත්වයෙන් පසුවේ',
    'නිරීක්ෂණයට අනුව, දරුවාට වැඩි අවධානයක් අවශ්ය වේ.',
    'හොඳයි',
    'හොඳ නැහැ',
    'මෙනුව වෙත ආපසු යන්න',
    'තනි ප්‍රතිචාරයක් සඳහා සාමාන්‍ය දරුවෙකුගේ සාමාන්‍ය කාලය',
    'තනි ප්‍රතිචාරයක් සඳහා ඔබේ දරුවා ගත කරන කාලය',
    'ඔබේ දරුවා ඉතා හොඳයි',
    'ඔබේ දරුවා හොඳයි, වැඩිදියුණු කිරීමට උත්සාහ කරන්න',
    'ඔබේ දරුවාට වැඩි අවධානයක් අවශ්යයි',
    'ඔබ',
    ' ජයගත් තරගය',
    ' පරාජයඋ තරගය',
    'ඊළඟට',
    'ප්‍රතිඵලය වෙත යන්න',
    'අදියර',
    'මෙම අදියරය වයස අවරුදු 5',
    'මෙම අදියරය වයස අවරුදු 6',
    'මෙම අදියරය වයස අවරුදු 7',
    'මෙනුව වෙත ආපසු යන්න',
    'තිරයේ පින්තුරයක් ගන්න',
  ],
];

export const ANIMAL_LANGUAGES = [
  ['Bird', 'Dog', 'Monkey', 'Zebra'],
  ['කුරුල්ලා', 'බල්ලා', 'වඳුරා', 'සීබ්‍රා'],
];

export const AUDIO_GAME_LANG = [
  [
    'Instructions for Game',
    'This game play with father, mother and child.',
    'Father should be sit on left side of child.',
    'Mother should be sit on right side of child.',
    'When game start, child should be focus on screen.',
    'The screen shows "Speak Father" or "Speak Mother" according to which parent needs to call the child.',
    'Game will detect child will response to father or mother.',
    'Speak Father',
    'Speak Mother',
    'Child respond to the voice of father',
    'Child respond to the voice of mother',
    'As per the observation, Child has good attention to voice of mother and father',
    'As per the observation, Child has not good attention to voice of mother and father',
  ],
  [
    'ක්‍රීඩාව සඳහා උපදෙස්',
    'මේ සෙල්ලම කරන්නේ දරුවා තාත්තා සහ අම්මා සමඟ.',
    'පියා දරුවාගේ වම් පැත්තේ වාඩි විය යුතුය.',
    'මව දරුවාගේ දකුණු පැත්තේ වාඩි විය යුතුය.',
    'ක්‍රීඩාව ආරම්භ කරන විට, දරුවා තිරය මත අවධානය යොමු කළ යුතුය.',
    'තිරයේ පෙන්වන්නේ "කතා කරන්න තාත්තා" හෝ "කතා කරන්න අම්මා" යන්න අනුව මාපියන්ට දරුවා ඇමතීමට අවශ්‍ය වේ.',
    'ක්‍රීඩාව දරුවා පියාට හෝ මවට ප්‍රතිචාර දක්වන බව හඳුනා ගනී.',
    'කතා කරන්න තාත්තා',
    'කතා කරන්න අම්මා',
    'දරුවා පියාගේ හඬට ප්රතිචාරය',
    'දරුවා මවගේ හඬට ප්රතිචාරය',
    'නිරීක්ෂණයට අනුව, දරුවා මවගේ සහ පියාගේ කටහඬ කෙරෙහි හොඳ අවධානයක් යොමු කරයි',
    'නිරීක්ෂණයට අනුව, දරුවා මවගේ සහ පියාගේ කටහඬ කෙරෙහි හොඳ අවධානයක් යොමු නොකරයි',
  ],
];

export const GAME_INSTRUCTION_SINHALA = [
  'na',
  'me sellama karanne dharuwa thaaththa saha amma samaga.',
  'piya dharuwage wam peththae wadiwenna.',
  'mawa dharuwage wam pette wadi wiya yuthuya.',
  'kreedawa aramba kranawita, daruwa thiraya matha awadanaya yomu kala yuthuya.',
  'thiraye penwanne katha kranna thaththa ho katha kranna amma yanna anuwa mapiyan daruwa amathima awashya we ',
  'kreedawa daruwa piyata homawata prathichara dakwana bawa haduna gani',
];

export default MENU_LANGUAGES;
